#!/usr/bin/env node

const { open } = require('node:fs/promises');
const { exec } = require("child_process");
const prependFile = require('prepend-file');
const tty = require('tty');
const fs = require('fs');
const inquirer = require('inquirer');
const fuzzy = require('fuzzy');

let commit_msg_filepath = process.argv[2];

inquirer.registerPrompt('autocomplete', require('inquirer-autocomplete-prompt'));

if (!process.stdin.isTTY) {
  const { O_RDONLY, O_NOCTTY } = fs.constants;
  let fd;
  try {
    fd = fs.openSync('/dev/tty', O_RDONLY + O_NOCTTY);
  } catch (error) {
    console.error('Please push your code in a terminal.');
    process.exit(1);
  }

  const stdin = new tty.ReadStream(fd);

  Object.defineProperty(process, 'stdin', {
    configurable: true,
    enumerable: true,
    get: () => stdin,
  });
}

let commitType = {
  type: 'autocomplete',
  name: 'type',
  message: 'What type of commit is this?',
  source: (...args) => searchTypes(...args),
}

function searchTypes(answers, input = '') {
  let choices = [
    'none',
    'feat',
    'fix',
    'chore',
    'refactor',
    'style',
    'revert',
    'test',
    'build',
    'perf',
    'ci',
    'docs',
  ];
  return new Promise(function(resolve) {
    let res = fuzzy.filter(input, choices);
    resolve(res.map(el => el.string));
  });
}

let commitScope = {
  type: 'autocomplete',
  name: 'scope',
  message: '(optional) What is the scope of this commit?',
  source: (...args) => searchScopes(...args),
  suggestOnly: true,
  when: (answers) => answers.type !== 'none',
}

async function searchScopes(answers, input = '') {
  let choices = await getPreviousScopes();
  
  return new Promise(function(resolve) {
    let res = fuzzy.filter(input, choices);
    resolve(res.map(el => el.string));
  });
}

function getPreviousScopes() {
  let cmd =`git log --pretty=format:%s -E --grep="^\\w+\\(.+\\)" --no-merges --all -1000`
  return new Promise((resolve, reject) => {
    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        console.log(`error: ${error.message}`);
        process.exit(1);
      }
      if (stderr) {
        console.log(`stderr: ${stderr}`);
        process.exit(1);
      }
      let scopes = [...new Set(stdout.split('\n').map( msg => getScope(msg) ))];
      resolve(scopes.filter(elm => !!elm));
    });
  });
}

function getScope(message) {
  const regex = /^\w+\((.+)\):/;
  if (!regex.test(message)) {
    return '';
  }

  return message.match(regex)[1];
}

let ticketNumber = {
  type: 'number',
  name: 'ticket',
  message: 'What is the ticket number?',
  default: getDefaultTicket,
  when: (answers) => answers.type !== 'none',
}

var ticketName = '';

function getDefaultTicket() {
  let cmd = 'git symbolic-ref --short HEAD';
  return new Promise((resolve, reject) => {
    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        console.log(`error: ${error.message}`);
        process.exit(1);
      }
      if (stderr) {
        console.log(`stderr: ${stderr}`);
        process.exit(1);
      }
      let ticketNumber = '';
      if (isBranchTicketValid(stdout)) {
        let ticketRegexArray =  getBranchTicket(stdout);
        ticketName  = ticketRegexArray[1];
        ticketNumber =  ticketRegexArray[2];
      }
      resolve(parseInt(ticketNumber));
    });
  });
}

function isBranchTicketValid(branch) {
  const regex = /^\w+\/(\w+)-\d+/g;
  return regex.test(branch);
}

function getBranchTicket(branch) {
  const regex = /^\w+\/(\w+)-(\d+)/;
  return branch.match(regex);
}

let questions = [
  commitType,
  commitScope,
  ticketNumber,
];

inquirer.prompt(questions).then( async(answers) => {
  if (answers.type === 'none') {
    process.exit(0);
  }
  const ticket = ticketName && answers.ticket ? "\n\n"+`${ticketName}-${answers.ticket}` : '';
  const scope = (answers.scope) ? `(${answers.scope})` : '';
  const prefix = `${answers.type + scope}: `

  const file = await open(commit_msg_filepath, 'a');
  await file.appendFile(ticket);
  await file.close();

  prependFile(commit_msg_filepath, prefix, (err) => {
    if (err) {
      process.exit(1);
    }
    process.exit(0);
  });
});

